### ISSUE TITLE
No passwword with EE2E 

### ISSUE THREAD

**Issue by Iwios** [markuman/nextcloud_collection#8]
Hi,
I will try to use nextcloud for my DevOps process.

I have the password module installed with encryption.

I try in another instance with password and no encryption.

The plyabook return a password from the nextcloud without encryption but with not working.

Im on Nextcloud 29 and password V2024.5.20

---
- name: Playbook to Retrieve Password
  hosts: localhost  # Spécifiez vos hôtes ici
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Assurez-vous que ce chemin est correct
  tasks:
    - name: Retrieve only Password with label "MariaDB"
      debug:
        var: lookup('markuman.nextcloud.passwords', 'test' , host='cloud.tld', cse_password='MyPasswordWith@', user='user', api_token='My Token', details=False)

PLAY [Playbook to Retrieve Password] *********************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [localhost]

TASK [Retrieve only Password with label "MariaDB"] *******************************************************************************************
ok: [localhost] => {
    "lookup('markuman.nextcloud.passwords', 'test' , host='cloud.tld', cse_password='MyPasswordWith@', user='user', api_token='My Token', details=False)": []
}

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by markuman** [comment]
@Iwios I cannot reproduce it using

* ansible [core 2.16.4]
* python 3.11.8
* pysodium 0.7.14
* nextcloud 29.0.0 with php 8.3.6
* passwords 2024.5.20


I use a test Instance for it.

```yml
---
- hosts: localhost

  tasks:
    - name: look for one password
      markuman.nextcloud.password_info:
        host: test.osuv.de
        user: admin
        api_token: M9D8o-TFYop-BeoNN-kQJKN-NN45S
        cse_password: lk7jh54rd5ez7kumh5zgee
        name: admin
      register: out

    - debug:
        var: out
```

results in

```
TASK [look for one password] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "out": {
        "changed": false,
        "failed": false,
        "password": [
            {
                "client": "Passwords Session 14.05.24 08:25 - admin@46.114.181.204",
                "created": 1715675364,
                "cseKey": "d78256a7-4ded-42a7-bf21-6df74aac01a5",
                "cseType": "CSEv1r1",
                "customFields": "[]",
                "editable": true,
                "edited": 1715675158,
                "favorite": false,
                "folder": "00000000-0000-0000-0000-000000000000",
                "hash": "5ad033df0fc866b67f7f4cb6ccf7ba456b63c254",
                "hidden": false,
                "id": "895b5dd6-91b5-4a76-95db-9c0320e16752",
                "label": "admin",
                "notes": "",
                "password": "LießenAusblickIndex",
                "revision": "92dce6cc-74c4-43a9-955d-68d1e4f6793a",
                "share": null,
                "shared": false,
                "sseType": "none",
                "status": 0,
                "statusCode": "GOOD",
                "trashed": false,
                "updated": 1715675364,
                "url": "",
                "username": "admin"
            }
        ]
    }
}
```

In generall, an empty list is returned (_like in your case_), when no item is found.   
For example, I search for the Item "admin1" and not for "admin" anymore.

```diff
--- passwords.yml       2024-05-14 10:38:20.618772408 +0200
+++ password1s.yml      2024-05-14 10:38:03.442122835 +0200
@@ -8,7 +8,7 @@
         user: admin
         api_token: M9D8o-TFYop-BeoNN-kQJKN-NN45S
         cse_password: lk7jh54rd5ez7kumh5zgee
-        name: admin
+        name: admin1
       register: out
     - debug:
         var: out
\ Kein Zeilenumbruch am Dateiende.
```

That will result in an empty list, becasue  "admin1" does not exist.

```
TASK [look for one password] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "out": {
        "changed": false,
        "failed": false,
        "password": []
    }
}
```

![grafik](https://github.com/markuman/markuman.nextcloud/assets/3920157/04d822ef-12be-4a02-ab3b-2e36727df8bf)

**Comment by markuman** [comment]
not reproducible ...closed so far.
